using Microsoft.CodeAnalysis;

namespace MyClassLibraryNetStandard2_0.SourceGenerators
{
    [Generator]
    public class MyGeneratedClassGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            //(optional)
        }
        public void Execute(GeneratorExecutionContext context)
        {
            string name = GetType().Name.Replace("Generator", "");
            string source = $@"//<auto-generated/>
using System;

namespace {GetType().Namespace}
{{
    public class {name}
    {{
        public void MyGeneratedMethod()
        {{
            Console.WriteLine(""Hello from generated method!"");
        }}
    }}
}}
";
            context.AddSource($"{GetType().Name}.g.cs", source);

        }
    }
}
