using Microsoft.CodeAnalysis;

namespace MyClassLibraryNetStandard2_0.SourceGenerators
{
    [Generator]
    public class MySourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            //(optional)
        }
        public void Execute(GeneratorExecutionContext context)
        {
            var partialType = "MyPartialGeneratedClass";
            //code generation
            string partialSource = PartialDefinitionSource(partialType);
            string source = PartialImplementationSource(partialType);
            context.AddSource($"{partialType}Definition.g.cs", partialSource);
            context.AddSource($"{partialType}Implementation.g.cs", source);

        }

        private string PartialImplementationSource(string partialType)
        {
            return $@"//<auto-generated/>
using System;

namespace {GetType().Namespace}
{{
    public partial class {partialType}
    {{
        static partial void MyPartialMethod()
        {{
            Console.WriteLine(""Hello from partial method!"");
        }}
    }}
}}
";
        }
        private string PartialDefinitionSource(string partialType)
        {
            return $@"//<auto-generated/>
using System;

namespace {GetType().Namespace}
{{
public partial class {partialType}
{{
    static partial void MyPartialMethod();
    public void RunPartialMethod()
    {{
        MyPartialMethod();
    }}
}}

}}
";
        }
    }
}
